# Generated by Django 6.1.1 on 2026-09-06 07:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={"ordering": ["due_date"]},
        ),
        migrations.AddField(
            model_name="child",
            name="allergies",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated, e.g. Penicillin, Peanuts. Leave blank if none known.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O+", "O Positive (O+)"),
                    ("O-", "O Negative (O-)"),
                    ("A+", "A Positive (A+)"),
                    ("A-", "A Negative (A-)"),
                    ("B+", "B Positive (B+)"),
                    ("B-", "B Negative (B-)"),
                    ("AB+", "AB Positive (AB+)"),
                    ("AB-", "AB Negative (AB-)"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public Hospital"),
                    ("private", "Private Hospital"),
                    ("clinic", "Clinic"),
                    ("health_centre", "Health Centre"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Out of 5, e.g. 4.8. Leave blank if not yet rated.",
                max_digits=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="services",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags shown as filters, e.g. Paediatrics, Immunisation, Emergency.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="immunizationrecord",
            name="dose_label",
            field=models.CharField(
                blank=True,
                help_text="e.g. Dose 3, Booster. Shown alongside the vaccine name.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.immunizationrecord",
            ),
        ),
        migrations.CreateModel(
            name="GrowthMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_on", models.DateField(default=datetime.date.today)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "height_percentile",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="e.g. 65 for 65th percentile.", null=True
                    ),
                ),
                (
                    "weight_percentile",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.child"
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_on"],
            },
        ),
    ]
