# Generated by Django 6.1.1 on 2026-09-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_reminder_options_child_allergies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health note"),
                            ("bill", "Bill paid"),
                            ("debt", "Outstanding debt"),
                        ],
                        default="health",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sw", "Kiswahili"),
                            ("lg", "Luganda"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("forwarded_to_whatsapp", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.parentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
